Evolution.UI/Models/ViewModel/ProductoViewModel.cs
using Evolution.Infraestructure.DTO;
using System;
using System.Collections.Generic;

namespace Evolution.UI.Models.ViewModel
{
    public class ProductoViewModel
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime UpdateTime { get; set; }
        public string ProDesc { get; set; }
        public decimal ProValor { get; set; }
        public List<ProductoDTO> ListProducto { get; set; }
    }
}

Evolution.UI/Controllers/ProductoController.cs
using AutoMapper;
using Evolution.Infraestructure.DTO;
using Evolution.UI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;

namespace Evolution.UI.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ILogger<ProductoController> _logger;
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;
        private readonly string _uri;

        public ProductoController(ILogger<ProductoController> logger,
                              IConfiguration configuration,
                              IMapper mapper)
        {
            _logger = logger;
            _configuration = configuration;
            _mapper = mapper;
            _uri = _configuration.GetValue<string>("UrlApi");
        }

        public async Task<IActionResult> IndexAsync()
        {
            ProductoViewModel model = new();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using var respuesta = await httpClient.GetAsync($"{_uri}Producto");
                    if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        var response = await respuesta.Content.ReadAsStringAsync();
                        await httpClient.GetStringAsync($"{_uri}Producto");
                        var listProducto = JsonSerializer.Deserialize<List<ProductoDTO>>(response,
                            new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                        model.ListProducto = listProducto;
                    }
                }
            }
            catch (WebException ex)
            {
                // Handle error
            }
            return View(model);
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(ProductoViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    var respuesta = await httpClient.PostAsJsonAsync($"{_uri}Producto", _mapper.Map<ProductoDTO>(model));

                    if (respuesta.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var cuerpo = await respuesta.Content.ReadAsStringAsync();
                        var erroresDelAPI = Util.Util.ExtraerErroresDelWebAPI(cuerpo);
                        List<string> ListError = new();
                        foreach (var campoErrores in erroresDelAPI)
                        {
                            string bodyError = string.Empty;
                            bodyError += $"-{campoErrores.Key}";
                            foreach (var error in campoErrores.Value)
                                bodyError += $"-{error}";
                            ListError.Add(bodyError);
                        }
                        TempData["message"] = ListError.ToString();
                    }
                    TempData["message"] = "Se registro correctamente la Producto";

                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            ProductoViewModel model = new();
            using (var httpClient = new HttpClient())
            {
                using var respuesta = await httpClient.GetAsync($"{_uri}Producto");
                if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                {
                    var response = await respuesta.Content.ReadAsStringAsync();
                    await httpClient.GetStringAsync($"{_uri}Producto");
                    var listProducto = JsonSerializer.Deserialize<List<ProductoDTO>>(response,
                        new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                    model = _mapper.Map<ProductoViewModel>(listProducto.Where(x => x.Id.Equals(id)).FirstOrDefault());
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateAsync(ProductoViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    await httpClient.PutAsJsonAsync($"{_uri}/Producto/{model.Id}", _mapper.Map<ProductoDTO>(model));
                    TempData["message"] = "Se actualizo correctamente la Producto";
                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    await httpClient.DeleteAsync($"{_uri}/Producto/{id}");
                    TempData["message"] = "Se Elimino correctamente la Producto";
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return RedirectToAction("Index");
        }
    }
}

Evolution.UI/Controllers/UsuarioController.cs
using AutoMapper;
using Evolution.Infraestructure.DTO;
using Evolution.UI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;

namespace Evolution.UI.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly ILogger<UsuarioController> _logger;
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;
        private readonly string _uri;

        public UsuarioController(ILogger<UsuarioController> logger,
                              IConfiguration configuration,
                              IMapper mapper)
        {
            _logger = logger;
            _configuration = configuration;
            _mapper = mapper;
            _uri = _configuration.GetValue<string>("UrlApi");
        }

        public async Task<IActionResult> IndexAsync()
        {
            UsuarioViewModel model = new();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using var respuesta = await httpClient.GetAsync($"{_uri}Usuario");
                    if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        var response = await respuesta.Content.ReadAsStringAsync();
                        await httpClient.GetStringAsync($"{_uri}Usuario");
                        var listUsuario = JsonSerializer.Deserialize<List<UsuarioDTO>>(response,
                            new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                        model.ListUsuario = listUsuario;
                    }
                }
            }
            catch (WebException ex)
            {
                // Handle error
            }
            return View(model);
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(UsuarioViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    var respuesta = await httpClient.PostAsJsonAsync($"{_uri}Usuario", _mapper.Map<UsuarioDTO>(model));

                    if (respuesta.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var cuerpo = await respuesta.Content.ReadAsStringAsync();
                        var erroresDelAPI = Util.Util.ExtraerErroresDelWebAPI(cuerpo);
                        List<string> ListError = new();
                        foreach (var campoErrores in erroresDelAPI)
                        {
                            string bodyError = string.Empty;
                            bodyError += $"-{campoErrores.Key}";
                            foreach (var error in campoErrores.Value)
                                bodyError += $"-{error}";
                            ListError.Add(bodyError);
                        }
                        TempData["message"] = ListError.ToString();
                    }
                    TempData["message"] = "Se registro correctamente la Usuario";

                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            UsuarioViewModel model = new();
            using (var httpClient = new HttpClient())
            {
                using var respuesta = await httpClient.GetAsync($"{_uri}Usuario");
                if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                {
                    var response = await respuesta.Content.ReadAsStringAsync();
                    await httpClient.GetStringAsync($"{_uri}Usuario");
                    var listUsuario = JsonSerializer.Deserialize<List<UsuarioDTO>>(response,
                        new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                    model = _mapper.Map<UsuarioViewModel>(listUsuario.Where(x => x.Id.Equals(id)).FirstOrDefault());
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateAsync(UsuarioViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    await httpClient.PutAsJsonAsync($"{_uri}/Usuario/{model.Id}", _mapper.Map<UsuarioDTO>(model));
                    TempData["message"] = "Se actualizo correctamente la Usuario";
                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    await httpClient.DeleteAsync($"{_uri}/Usuario/{id}");
                    TempData["message"] = "Se Elimino correctamente la Usuario";
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return RedirectToAction("Index");
        }
    }
}

Evolution.UI/Views/Producto/Create.cshtml
@using  Evolution.UI.Models.ViewModel;
@model ProductoViewModel
@{
    ViewData["Title"] = "Registro Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3> Crear Nueva Producto</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <form asp-action="Create" asp-controller="Producto" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="ProDesc" class="control-label"></label>
                        <input type="text" asp-for="ProDesc" class="form-control" placeholder="Descripcion">
                        <span asp-validation-for="ProDesc" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="ProValor" class="control-label"></label>
                        <input type="text" asp-for="ProValor" class="form-control" placeholder="Valor">
                        <span asp-validation-for="ProValor" class="text-danger"></span>
                    </div>
                </div>
                <hr>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Registrar">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}

Evolution.UI/Views/Producto/Index.cshtml
@using  Evolution.UI.Models.ViewModel;
@model ProductoViewModel
@{
    ViewData["Title"] = "Producto";
}
<div class="container">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["message"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3> Listado</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Producto">Crear nuevo registro</a>
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        @if (Model?.ListProducto?.Count() > 0)
        {
            <table class="table table-bordered table-striped" id="Table">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.ProDesc)</td>
                        <td>@Html.DisplayNameFor(m => m.ProValor)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListProducto)
                    {
                        <tr>
                            <td>@item.ProDesc</td>
                            <td>@item.ProValor</td>
                            <td>
                                <a asp-controller="Usuario" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                                <a asp-controller="Usuario" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No se encuentra registros </p>
        }
    </div>
</div>

Evolution.UI/Views/Producto/Update.cshtml
@using  Evolution.UI.Models.ViewModel;
@model ProductoViewModel
@{
    ViewData["Title"] = "Editar Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3> Editar Producto</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <form asp-action="Update" asp-controller="Producto" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="ProDesc" class="control-label"></label>
                        <input type="text" asp-for="ProDesc" class="form-control" placeholder="Descripcion">
                        <span asp-validation-for="ProDesc" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="ProValor" class="control-label"></label>
                        <input type="text" asp-for="ProValor" class="form-control" placeholder="Valor">
                        <span asp-validation-for="ProValor" class="text-danger"></span>
                    </div>
                </div>
s
                <hr>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Editar">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}