Evolution.UI/Models/ViewModel/PedidoViewModel.cs
using Evolution.Infraestructure.DTO;
using System;
using System.Collections.Generic;

namespace Evolution.UI.Models.ViewModel
{
    public class PedidoViewModel
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime UpdateTime { get; set; }
        public int PedUsu { get; set; }
        public int PedProd { get; set; }
        public decimal PedVrUnit { get; set; }
        public float PedCant { get; set; }
        public decimal PedSubTot { get; set; }
        public float PedIVA { get; set; }
        public decimal PedTotal { get; set; }
        public UsuarioDTO Usuario { get; set; }
        public ProductoDTO Producto { get; set; }
        public List<PedidoDTO> ListPedido { get; set; }
    }
}

Evolution.UI/Controllers/PedidoController.cs
using AutoMapper;
using Evolution.Infraestructure.DTO;
using Evolution.UI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;

namespace Evolution.UI.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ILogger<PedidoController> _logger;
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;
        private readonly string _uri;

        public PedidoController(ILogger<PedidoController> logger,
                              IConfiguration configuration,
                              IMapper mapper)
        {
            _logger = logger;
            _configuration = configuration;
            _mapper = mapper;
            _uri = _configuration.GetValue<string>("UrlApi");
        }

        public async Task<IActionResult> IndexAsync()
        {
            PedidoViewModel model = new();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using var respuesta = await httpClient.GetAsync($"{_uri}Pedido");
                    if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        var response = await respuesta.Content.ReadAsStringAsync();
                        await httpClient.GetStringAsync($"{_uri}Pedido");
                        var listPedido = JsonSerializer.Deserialize<List<PedidoDTO>>(response,
                            new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                        model.ListPedido = listPedido;
                        BuidModel();
                    }
                }
            }
            catch (WebException ex)
            {
                // Handle error
            }
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            List<ProductoDTO> listProducto = new();
            List<UsuarioDTO> listUsuario = new();
            listProducto = await GetProductDTO();
            listUsuario = await GetUsuarioDTO();
            ViewBag.ListUsuario = new SelectList(listUsuario, "Id", "UsuNombre");
            ViewBag.ListProducto = new SelectList(listProducto, "Id", "ProDesc");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(PedidoViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    var respuesta = await httpClient.PostAsJsonAsync($"{_uri}Pedido", _mapper.Map<PedidoDTO>(model));

                    if (respuesta.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var cuerpo = await respuesta.Content.ReadAsStringAsync();
                        var erroresDelAPI = Util.Util.ExtraerErroresDelWebAPI(cuerpo);
                        List<string> ListError = new();
                        foreach (var campoErrores in erroresDelAPI)
                        {
                            string bodyError = string.Empty;
                            bodyError += $"-{campoErrores.Key}";
                            foreach (var error in campoErrores.Value)
                                bodyError += $"-{error}";
                            ListError.Add(bodyError);
                        }
                        TempData["message"] = ListError.ToString();
                    }
                    TempData["message"] = "Se registro correctamente la Pedido";

                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            PedidoViewModel model = new();
            using (var httpClient = new HttpClient())
            {
                using var respuesta = await httpClient.GetAsync($"{_uri}Pedido");
                if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                {
                    var response = await respuesta.Content.ReadAsStringAsync();
                    await httpClient.GetStringAsync($"{_uri}Pedido");
                    var listPedido = JsonSerializer.Deserialize<List<PedidoDTO>>(response,
                        new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                    model = _mapper.Map<PedidoViewModel>(listPedido.Where(x => x.Id.Equals(id)).FirstOrDefault());
                    List<ProductoDTO> listProducto = new();
                    List<UsuarioDTO> listUsuario = new();
                    listProducto = await GetProductDTO();
                    listUsuario = await GetUsuarioDTO();
                    ViewBag.ListUsuario = new SelectList(listUsuario, "Id", "UsuNombre");
                    ViewBag.ListProducto = new SelectList(listProducto, "Id", "ProDesc");
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateAsync(PedidoViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    await httpClient.PutAsJsonAsync($"{_uri}/Pedido/{model.Id}", _mapper.Map<PedidoDTO>(model));
                    TempData["message"] = "Se actualizo correctamente la Pedido";
                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    await httpClient.DeleteAsync($"{_uri}/Pedido/{id}");
                    TempData["message"] = "Se Elimino correctamente la Pedido";
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return RedirectToAction("Index");
        }

        private async Task<List<ProductoDTO>> GetProductDTO()
        {
            List<ProductoDTO> model = new();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using var respuesta = await httpClient.GetAsync($"{_uri}Producto");
                    if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        var response = await respuesta.Content.ReadAsStringAsync();
                        await httpClient.GetStringAsync($"{_uri}Producto");
                        var list = JsonSerializer.Deserialize<List<ProductoDTO>>(response,
                            new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                        model = list;
                    }
                }
                return model;
            }
            catch (WebException ex)
            {
                return model;
            }
        }
        private async Task<List<UsuarioDTO>> GetUsuarioDTO()
        {
            List<UsuarioDTO> model = new();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using var respuesta = await httpClient.GetAsync($"{_uri}Usuario");
                    if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        var response = await respuesta.Content.ReadAsStringAsync();
                        await httpClient.GetStringAsync($"{_uri}Usuario");
                        var list = JsonSerializer.Deserialize<List<UsuarioDTO>>(response,
                            new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                        model = list;
                    }
                }
                return model;
            }
            catch (WebException ex)
            {
                return model;
            }
        }
        private async void BuidModel()
        {
            List<ProductoDTO> listProducto = new();
            List<UsuarioDTO> listUsuario = new();
            listProducto = await GetProductDTO();
            listUsuario = await GetUsuarioDTO();
            ViewBag.ListUsuario = new SelectList(listUsuario, "Id", "UsuNombre");
            ViewBag.ListProducto = new SelectList(listProducto, "Id", "ProDesc");
        }
    }
}

Evolution.UI/Views/Pedido/Create.cshtml
@using Evolution.UI.Models.ViewModel;
@model PedidoViewModel
@{
    ViewData["Title"] = "Registro Pedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var listUsuario = ViewBag.ListUsuario;
    var listproducto = ViewBag.ListProducto;
}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3> Crear Nueva Pedido</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <form asp-action="Create" asp-controller="Pedido" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedVrUnit" class="control-label"></label>
                        <input type="text" asp-for="PedVrUnit" class="form-control">
                        <span asp-validation-for="PedVrUnit" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedCant" class="control-label"></label>
                        <input type="text" asp-for="PedCant" class="form-control">
                        <span asp-validation-for="PedCant" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedSubTot" class="control-label"></label>
                        <input type="text" asp-for="PedSubTot" class="form-control">
                        <span asp-validation-for="PedSubTot" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedIVA" class="control-label"></label>
                        <input type="text" asp-for="PedIVA" class="form-control">
                        <span asp-validation-for="PedIVA" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedTotal" class="control-label"></label>
                        <input type="text" asp-for="PedTotal" class="form-control">
                        <span asp-validation-for="PedTotal" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedUsu" class="control-label"></label>
                        <select asp-for="PedUsu" class="form-control"
                                asp-items="@listUsuario">
                            <option value="">-- Select item --</option>
                        </select>
                        <span asp-validation-for="PedUsu" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedProd" class="control-label"></label>
                        <select asp-for="PedProd" class="form-control"
                                asp-items="@listproducto">
                            <option value="">-- Select item --</option>
                        </select>
                        <span asp-validation-for="PedProd" class="text-danger" />
                    </div>
                </div>
                <hr>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Registrar">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

<partial name="_ValidationScriptsPartial" />
}

Evolution.UI/Views/Pedido/Index.cshtml
@using  Evolution.UI.Models.ViewModel;
@model PedidoViewModel
@{
    ViewData["Title"] = "Producto";
}
<div class="container">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["message"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3> Listado</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Pedido">Crear nuevo registro</a>
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        @if (Model?.ListPedido?.Count() > 0)
        {
            <table class="table table-bordered table-striped" id="Table">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.PedVrUnit)</td>
                        <td>@Html.DisplayNameFor(m => m.PedCant)</td>
                        <td>@Html.DisplayNameFor(m => m.PedSubTot)</td>
                        <td>@Html.DisplayNameFor(m => m.PedIVA)</td>
                        <td>@Html.DisplayNameFor(m => m.PedTotal)</td>
                        <td>@Html.DisplayNameFor(m => m.Usuario.UsuNombre)</td>
                        <td>@Html.DisplayNameFor(m => m.Producto.ProDesc)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListPedido)
                    {
                        <tr>
                            <td>@item.PedVrUnit</td>
                            <td>@item.PedCant</td>
                            <td>@item.PedSubTot</td>
                            <td>@item.PedIVA</td>
                            <td>@item.PedTotal</td>
                            <td>@item.Usuario.UsuNombre</td>
                            <td>@item.Producto.ProDesc</td>
                            <td>
                                <a asp-controller="Pedido" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                                <a asp-controller="Pedido" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No se encuentra registros </p>
        }
    </div>
</div>

Evolution.UI/Views/Pedido/Update.cshtml
@using  Evolution.UI.Models.ViewModel;
@model PedidoViewModel
@{
    ViewData["Title"] = "Editar Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3> Editar Producto</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <form asp-action="Update" asp-controller="Pedido" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedVrUnit" class="control-label"></label>
                        <input type="text" asp-for="PedVrUnit" class="form-control" >
                        <span asp-validation-for="PedVrUnit" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedCant" class="control-label"></label>
                        <input type="text" asp-for="PedCant" class="form-control" >
                        <span asp-validation-for="PedCant" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedSubTot" class="control-label"></label>
                        <input type="text" asp-for="PedSubTot" class="form-control" >
                        <span asp-validation-for="PedSubTot" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedIVA" class="control-label"></label>
                        <input type="text" asp-for="PedIVA" class="form-control" >
                        <span asp-validation-for="PedIVA" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedTotal" class="control-label"></label>
                        <input type="text" asp-for="PedTotal" class="form-control" >
                        <span asp-validation-for="PedTotal" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedUsu" class="control-label"></label>
                        <select asp-for="PedUsu" class="form-control"
                                asp-items="@ViewBag.ListUsuario">
                            <option value="">-- Select item --</option>
                        </select>
                        <span asp-validation-for="PedUsu" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="PedProd" class="control-label"></label>
                        <select asp-for="PedProd" class="form-control"
                                asp-items="@ViewBag.ListProducto">
                            <option value="">-- Select item --</option>
                        </select>
                        <span asp-validation-for="PedProd" class="text-danger" />
                    </div>
                </div>
                <hr>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Editar">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}